use different ports between tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,7 +29,24 @@ jobs:
       - run: cd $HOME && for version in $VERSIONS; do export GOROOT=$HOME/go_root_$version/go; export PATH=$GOROOT/bin/:$PATH; export GOPATH=$HOME/go_path_$version; go test -v github.com/cossacklabs/acra/...; if [ "$?" != "0" ]; then echo "$version" >> "$FILEPATH_ERROR_FLAG"; fi done
       # if file exists (exit code of stat == 0 ) then something was wrong. cat file with versions of environments where was error and return exit 1
       - run: if [ -f  $FILEPATH_ERROR_FLAG ]; then cat "$FILEPATH_ERROR_FLAG"; rm "$FILEPATH_ERROR_FLAG"; exit 1; fi
-      - run: cd $HOME/project && for version in $VERSIONS; do export GOROOT=$HOME/go_root_$version/go; export PATH=$GOROOT/bin/:$PATH; export GOPATH=$HOME/go_path_$version; python3 tests/test.py; if [ "$?" != "0" ]; then echo "$version" >> "$FILEPATH_ERROR_FLAG"; fi done
+      - run:
+        command: |
+        cd $HOME/project &&
+        for version in $VERSIONS; do
+        export TEST_ACRA_PORT=$(expr ${TEST_ACRA_PORT} + 1);
+        export TEST_PROXY_PORT=$(expr ${TEST_PROXY_PORT} + 1);
+        export TEST_PROXY_COMMAND_PORT=$(expr ${TEST_PROXY_COMMAND_PORT} + 1);
+        export GOROOT=$HOME/go_root_$version/go;
+        export PATH=$GOROOT/bin/:$PATH;
+        export GOPATH=$HOME/go_path_$version;
+        python3 tests/test.py;
+        if [ "$?" != "0" ]; then echo "$version" >> "$FILEPATH_ERROR_FLAG"; 
+        fi done
+
+        environment:
+        TEST_ACRA_PORT=6000
+        TEST_PROXY_PORT=7000
+        TEST_PROXY_COMMAND_PORT=8000
 
 workflows:
   version: 2
